export enum ActivityType {
  TICKET = 'TICKET',
  RENTAL = 'RENTAL',
  ACCOMMODATION = 'ACCOMMODATION',
  MERCHANDISE = 'MERCHANDISE',
  MEMBERSHIP = 'MEMBERSHIP',
  SERVICE = 'SERVICE',
  ADD_ON_PRODUCTS = 'ADD_ON_PRODUCTS',
  EVENTS = 'EVENTS',
  GIFT_CARD = 'GIFT_CARD',
}
