export enum CHECKOUT_FORM_FIELD_TYPE {
  NAME = 'NAME',
  NUMBER = 'NUMBER',
  CALENDAR = 'CALENDAR',
  TERMS_CHECKBOX = 'TERMS_CHECKBOX',
  EXTRA_INFO = 'EXTRA_INFO',
  OPTIONS = 'OPTIONS',
  FREE_TEXT = 'FREE_TEXT',
}
